const restaurants = [
  {
    id: '',
    name: 'Dominoes Pizza',
    cuisineType: [
      'pizza',
      'fast food',
      'pizza',
      'fast food',
      'pizza',
      'fast food',
      'pizza',
      'fast food',
    ],

    description: '',
    rating: 4.6,
    eta: 1800,
    costPerPerson: 280,
    restaurantImage: '/dominoes.avif',
    footItems: [
      {
        id: Math.random(),
        name: 'Corn Pizza',
        price: 200,
      },
      {
        id: Math.random(),
        name: 'Onion Pizza',
        price: 200,
      },
      {
        id: Math.random(),
        name: 'Cheese Pizza',
        price: 200,
      },
      {
        id: Math.random(),
        name: 'Cheese Pizza',
        price: 200,
      },
    ],
  },
  {
    id: '',
    name: 'Dominoes Pizza',
    cuisineType: ['pizza', 'fast food'],
    description: '',
    rating: 4.6,
    eta: 1800,
    costPerPerson: 280,
    restaurantImage: '/dominoes.avif',
  },
  {
    id: '',
    name: 'Dominoes Pizza',
    cuisineType: ['pizza', 'fast food'],
    description: '',
    rating: 4.6,
    eta: 1800,
    costPerPerson: 280,
    restaurantImage: '/dominoes.avif',
  },
  {
    id: '',
    name: 'Dominoes Pizza',
    cuisineType: ['pizza', 'fast food'],
    description: '',
    rating: 4.6,
    eta: 1800,
    costPerPerson: 280,
    restaurantImage: '/dominoes.avif',
  },
  {
    id: '',
    name: 'Dominoes Pizza',
    cuisineType: ['pizza', 'fast food'],
    description: '',
    rating: 4.6,
    eta: 1800,
    costPerPerson: 280,
    restaurantImage: '/dominoes.avif',
  },
  {
    id: '',
    name: 'Dominoes Pizza',
    cuisineType: ['pizza', 'fast food'],
    description: '',
    rating: 4.6,
    eta: 1800,
    costPerPerson: 280,
    restaurantImage: '/dominoes.avif',
  },
];

export { restaurants };
